name: Run PubMed Fetcher

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run script
        run: poetry run python -m pubmed_paper_fetcher.cli "COVID-19 vaccine"
